version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: pharmacy25_user
      POSTGRES_DB: pharmacy25
      POSTGRES_PASS: pharmacy25
    volumes:
      - pgdata:/var/lib/posgresql/data
  zuri:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata:
